name: huda-net
services:
    php:
        restart: unless-stopped
        image: php:8.3-fpm-alpine3.20
        build:
            context: .
            dockerfile: Dockerfile
        # volumes:
        #     - ./:/var/www/html:cached
        depends_on:
            - db
        networks:
            - laravel-network
        # mem_limit: 0.5G
        # cpus: 0.5
    db:
        image: mariadb:latest
        # container_name: mariadb_latest
        restart: unless-stopped
        environment:
            MARIADB_ROOT_HOST: maria_db
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: huda_net
            MARIADB_USER: user
            MARIADB_PASSWORD: 1234
        # ports:
        #     - "3307:3306"
        # volumes:
        #     - ./mariadb_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html:cached
            - ./nginx/ssl:/etc/nginx/ssl
        depends_on:
            - php
        networks:
            - laravel-network
        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 1G
                reservations:
                    cpus: 0.25
                    memory: 256M
networks:
    laravel-network:
        driver: bridge
